### ISSUE TITLE
2.79 Code

### ISSUE THREAD

**Issue by stefream** [TactileUniverse/3D-Printed-Galaxy-Software#17]
I saw that you guys had updated your code to 2.8 blender, but I was wondering if you would be willing to reupload the 2.79 code as that is what my team uses for our projects. Or, is there a better way to upload it? I cannot get emboss planes function to work on the newer system.

**Comment by CKrawczyk** [comment]
Links to all previous versions can be found on the releases page https://github.com/TactileUniverse/3D-Printed-Galaxy-Software/releases
